---
- name: Obtener información de la distribución Linux
  hosts: servidores
  gather_facts: no
  tasks:
    - name: Ejecutar lsb_release -a
      command: lsb_release -a
      register: lsb_output
      changed_when: false

    - name: Mostrar resultado de lsb_release
      debug:
        var: lsb_output.stdout_lines
