---
- name: Actualizar minipc-insumos-produccion
  hosts: insumos-produccion
  become: yes 
  tasks:
    - name: Actualizar la lista de paquetes
      apt:
        update_cache: yes

    - name: Actualizar paquetes instalados
      apt:
        upgrade: full
        autoremove: yes
        autoclean: yes
